stages: [test, dist]

before_script:
    - export V=1 MAKEFLAGS="-j$(mk/nproc.sh)"

test:dynamic:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/vala-debian
    script:
        - apt-get update && apt-get -y install libmarkdown2-dev
        - make
        - ldd showdown | grep libmarkdown
        - du showdown
        - make install

test:static:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/vala-debian
    script:
        - make USE_LOCAL_DISCOUNT=1
        - ldd showdown | grep libmarkdown
        - du showdown
        - make install

pages:
    stage: dist
    image: registry.gitlab.com/craigbarnes/dockerfiles/vala-debian
    artifacts: {paths: [public]}
    only: [master]
    script:
        - flatpak -v remote-add gnome https://sdk.gnome.org/gnome.flatpakrepo
        - flatpak -v install gnome org.gnome.Platform 3.26
        - flatpak -v install gnome org.gnome.Sdk 3.26
        - echo "$GPG_PRIVATE_KEY" | gpg --import -
        - make flatpak FLATPAK_EXPORT_FLAGS='--gpg-sign=43705BA1'
        - echo "$GPG_PUBLIC_KEY" | flatpak -v remote-add --gpg-import=- showdown public/flatpak/
        - flatpak -v install showdown io.gitlab.craigbarnes.Showdown
        - flatpak info io.gitlab.craigbarnes.Showdown
