stages: [build, dist]

before_script:
    - export V=1 MAKEFLAGS="-j$(mk/nproc.sh)"

build:debian:
    stage: build
    image: registry.gitlab.com/craigbarnes/dockerfiles/vala-debian
    script:
        - make USE_LOCAL_DISCOUNT=1
        - du -h showdown
        - make install
        - apt-get update && apt-get -y install libmarkdown2-dev
        - make
        - ldd showdown | grep libmarkdown
        - du -h showdown
        - make install

pages:
    stage: dist
    image: registry.gitlab.com/craigbarnes/dockerfiles/flatpak-debian
    artifacts: {paths: [public]}
    only: [master]
    script:
        - echo "$GPG_PRIVATE_KEY" | gpg --import -
        - mkdir -p public/
        - flatpak-builder --gpg-sign=43705BA1 --repo=public/flatpak/
          build/flatpak/ io.gitlab.craigbarnes.Showdown.json
        - cp res/showdown.svg showdown.flatpakref public/
        - echo "$GPG_PUBLIC_KEY" | flatpak -v remote-add --gpg-import=- showdown public/flatpak/
        - flatpak -v install showdown io.gitlab.craigbarnes.Showdown
        - flatpak info io.gitlab.craigbarnes.Showdown
