stages: [test, dist]

test:dynamic:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/vala
    script:
        - apt-get update
        - apt-get install -qy libmarkdown2-dev meson
        - make
        - make install
        - meson build/meson/
        - ninja -C build/meson/ install

test:static:
    stage: test
    image: registry.gitlab.com/craigbarnes/dockerfiles/vala
    script:
        - make USE_LOCAL_DISCOUNT=1
        - make install

pages:
    stage: dist
    image: debian:stretch
    artifacts: {paths: [public]}
    only: [master]
    script:
        - apt-get update
        - apt-get install -qy flatpak curl make git gnupg ca-certificates
        - flatpak -v remote-add gnome https://sdk.gnome.org/gnome.flatpakrepo
        - flatpak -v install gnome org.gnome.Platform 3.24
        - flatpak -v install gnome org.gnome.Sdk 3.24
        - echo "$GPG_PRIVATE_KEY" | gpg --import -
        - make flatpak FLATPAK_EXPORT_FLAGS='--gpg-sign=43705BA1'
        - echo "$GPG_PUBLIC_KEY" | flatpak -v remote-add --gpg-import=- showdown public/flatpak/
        - flatpak -v install showdown org.gnome.Showdown
        - flatpak info org.gnome.Showdown
        - make -j`nproc` check-dist
