tests:
    image: registry.gitlab.com/craigbarnes/dockerfiles/vala
    script:
        - make USE_LOCAL_DISCOUNT=1

pages:
    image: debian:stretch
    artifacts: {paths: [public]}
    only: [master]
    script:
        - apt-get update
        - apt-get install -qy flatpak curl make git ca-certificates
        - flatpak -v remote-add gnome https://sdk.gnome.org/gnome.flatpakrepo
        - flatpak -v install gnome org.gnome.Platform 3.22
        - flatpak -v install gnome org.gnome.Sdk 3.22
        - make flatpak
        - flatpak -v remote-add --no-gpg-verify showdown public/flatpak/
        - flatpak -v install showdown org.gnome.Showdown
        - flatpak info org.gnome.Showdown
        - make -j`nproc` check-dist
