stages:
    - build
    - check

pages:
    stage: build
    image: debian:stretch
    artifacts: {paths: [public]}
    only: [master]
    script:
        - apt-get update
        - apt-get install -qy flatpak curl make ca-certificates
        - flatpak -v remote-add gnome https://sdk.gnome.org/gnome.flatpakrepo
        - flatpak -v install gnome org.gnome.Platform 3.22
        - flatpak -v install gnome org.gnome.Sdk 3.22
        - make flatpak FLATPAK_EXPORT_FLAGS=
        - flatpak -v remote-add --no-gpg-verify showdown public/flatpak/
        - flatpak -v install showdown org.gnome.Showdown
        - flatpak info org.gnome.Showdown

check-install:
    stage: check
    image: debian:stretch
    only: [master]
    script:
        - apt-get update
        - apt-get install -qy flatpak ca-certificates
        - flatpak list --show-details
        - flatpak install -y https://craigbarnes.gitlab.io/showdown/showdown.flatpakref
        - flatpak list --show-details
        - flatpak info org.gnome.Showdown
